
DO BEGIN
    DECLARE TURMA_PEDIDO VARCHAR(255) = '{turma}';
    DECLARE CARTEIRA_PEDIDO VARCHAR(255) = '{cart}';
    DECLARE DATA_PEDIDO_A DATE  = '{data}';



    IF CARTEIRA_PEDIDO = 'MISTA' THEN
        SELECT   UTD, ZONA, QTD_MIN AS NUM_CORTES_MIN, QTD_MAX AS NUM_CORTES_IDEAL, CAST(RAIO_MIN*1000 AS int) AS RAIO_IDEAL, 
            CAST(RAIO_MAX*1000 AS int) AS RAIO_MAX, CAST(RAIO_INC*1000 AS int) AS RAIO_STEP,CARTEIRA,TURMA,
            CAST (SUBSTRING (QTD_CLUSTERS,
                      2*WEEKDAY(DATA_PEDIDO_A)+1,2) AS int) AS CLUSTERS

            FROM CLB142840.CLUSTER_CONFIG5
            WHERE TURMA = TURMA_PEDIDO AND
            CARTEIRA IN ('CONVENCIONAL','RECORTE');

    ELSE

        SELECT   UTD, ZONA, QTD_MIN AS NUM_CORTES_MIN, QTD_MAX AS NUM_CORTES_IDEAL, CAST(RAIO_MIN*1000 AS int) AS RAIO_IDEAL, 
                CAST(RAIO_MAX*1000 AS int) AS RAIO_MAX, CAST(RAIO_INC*1000 AS int) AS RAIO_STEP,CARTEIRA,TURMA,
                CAST(SUBSTRING (QTD_CLUSTERS,
                          2*WEEKDAY(DATA_PEDIDO_A)+1,2)AS int)AS CLUSTERS /*, '' AS SERVICO */
                FROM CLB142840.CLUSTER_CONFIG5
                WHERE CARTEIRA = CARTEIRA_PEDIDO
                AND TURMA = TURMA_PEDIDO; 
    END IF;

END;