
DO BEGIN
    DECLARE TURMA_PEDIDO VARCHAR(255) = '{turma}';
    DECLARE CARTEIRA_PEDIDO VARCHAR(255) = '{cart}';
    DECLARE DATA_PEDIDO_A DATE  = '{data}';

    --TURMA
    --DATA
    --EXTRA
    --SERVICO


    IF CARTEIRA_PEDIDO = 'MISTA' THEN
        SELECT   UTD, ZONA, QTD_MIN, QTD_MAX, CAST(RAIO_MIN*1000 AS int) AS RAIO_IDEAL, 
            CAST(RAIO_MAX*1000 AS int) AS RAIO_MAX, CAST(RAIO_INC*1000 AS int) AS RAIO_STEP,CARTEIRA,TURMA,
            CAST (SUBSTRING (QTD_CLUSTERS,
                      2*WEEKDAY(DATA_PEDIDO_A)+1,2) AS int) AS CLUSTERS,
            '' AS PREENCHER,
            '' AS QTD_PREENCHER

            FROM CLB142840.CLUSTER_CONFIG5
            WHERE TURMA = TURMA_PEDIDO AND
            CARTEIRA IN ('CONVENCIONAL','RECORTE');

    ELSEIF CARTEIRA_PEDIDO = 'RECORTE' THEN
    
    SELECT UTD, CC.ZONA, CC.QTD_MIN, CC.QTD_MAX, CAST(RAIO_MIN*1000 AS int) AS RAIO_IDEAL, 
            CAST(RAIO_MAX*1000 AS int) AS RAIO_MAX, CAST(RAIO_INC*1000 AS int) AS RAIO_STEP,CC.CARTEIRA,TURMA,
            CAST (SUBSTRING (QTD_CLUSTERS,
                      2*WEEKDAY(DATA_PEDIDO_A)+1,2) AS int) AS CLUSTERS,
        CASE WHEN 
            BM.QTD_MIN IS NULL THEN 0
            ELSE BM.QTD_MIN  END AS QTD_PREENCHER, 
        CASE WHEN	
            BM.CARTEIRA IS NULL THEN ''
            ELSE BM.CARTEIRA END AS PREENCHER FROM (
            (SELECT * FROM CLB142840.CLUSTER_CONFIG5 
            WHERE CARTEIRA = 'RECORTE'
            AND TURMA = 'EPS' 
            )) AS CC 

        LEFT JOIN  (SELECT * FROM (SELECT ZONA, QTD_MIN, CARTEIRA FROM CLB142840.CLUSTER_CONFIG5 
        WHERE CARTEIRA = 'BAIXA MIX')) AS BM
        ON BM.ZONA = CC.ZONA;

    ELSE     

        SELECT   UTD, ZONA, QTD_MIN, QTD_MAX, CAST(RAIO_MIN*1000 AS int) AS RAIO_IDEAL, 
                CAST(RAIO_MAX*1000 AS int) AS RAIO_MAX, CAST(RAIO_INC*1000 AS int) AS RAIO_STEP,CARTEIRA,TURMA,
                CAST(SUBSTRING (QTD_CLUSTERS,
                          2*WEEKDAY(DATA_PEDIDO_A)+1,2)AS int)AS CLUSTERS,
                '' AS PREENCHER,
                '' AS QTD_PREENCHER
              
                FROM CLB142840.CLUSTER_CONFIG5
                WHERE CARTEIRA = CARTEIRA_PEDIDO
                AND TURMA = TURMA_PEDIDO; 
    END IF;

END;