
SELECT UTD,
TURMA,
QTD_GERADAS,
PECLD_GERADAS,
TICKET_PECLD_GERADAS,
CARTEIRA,
ZCGDTNOTA,
DAYOFMONTH(ZCGDTNOTA) || DIA_SEMANA   as DIA_MES,
QTD_EXECUTADAS, 
PECLD_EXECUTADAS, 
TICKET_PECLD_EXECUTADAS, 
QTD_ANULADAS, 
QTD_DEFASAGEM
 FROM (
SELECT 
CASE WHEN DAYOFWEEK(BASE_GERADAS.ZCGDTNOTA) = 2 THEN ' (seg)' 
WHEN DAYOFWEEK(BASE_GERADAS.ZCGDTNOTA) = 3 THEN ' (ter)' 
WHEN DAYOFWEEK(BASE_GERADAS.ZCGDTNOTA) = 4 THEN ' (qua)'
WHEN DAYOFWEEK(BASE_GERADAS.ZCGDTNOTA) = 5 THEN ' (qui)'
WHEN DAYOFWEEK(BASE_GERADAS.ZCGDTNOTA) = 6 THEN ' (sex)'
WHEN DAYOFWEEK(BASE_GERADAS.ZCGDTNOTA) = 7 THEN ' (sab)'
WHEN DAYOFWEEK(BASE_GERADAS.ZCGDTNOTA) = 1 THEN ' (dom)'
END AS DIA_SEMANA,
BASE_GERADAS.UTD, BASE_GERADAS.TURMA, QTD_GERADAS, PECLD_GERADAS, TICKET_PECLD_GERADAS, BASE_GERADAS.CARTEIRA, BASE_GERADAS.ZCGDTNOTA, QTD_EXECUTADAS, PECLD_EXECUTADAS, TICKET_PECLD_EXECUTADAS, QTD_ANULADAS, QTD_DEFASAGEM FROM (
SELECT 

UTD40 AS UTD,TURMA, 
--ZCGTPNOTA AS TIPO_NOTA, 
SUM(QTDE) AS QTD_GERADAS, 
SUM(PECLD) AS PECLD_GERADAS,  
SUM(PECLD)/SUM(QTDE) AS TICKET_PECLD_GERADAS,
CASE 
	WHEN ZCGTPNOTA = 'CS' THEN 'CORTE' 
	WHEN ZCGTPNOTA = 'CA' THEN 'RECORTE'
	WHEN ZCGTPNOTA = 'CB' THEN 'BAIXA' END AS CARTEIRA,
ZCGDTNOTA
FROM (
SELECT 
 CL.REGIONAL40,
 CL.SETOR40,
 CL.UTD40,	 

 BASE.ZCGTPNOTA,
 BASE.ZCGDTNOTA,
 
 
 
 CASE WHEN (WEEKDAY(BASE.ZCGDTNOTA) < 5 AND BASE.ZCGHRNOTA > '15') OR WEEKDAY(BASE.ZCGDTNOTA) = 6 THEN NEXT_DAY(BASE.ZCGDTNOTA) 
	  WHEN  WEEKDAY(BASE.ZCGDTNOTA) = 5 AND BASE.ZCGHRNOTA > '15' THEN ADD_DAYS(BASE.ZCGDTNOTA,2) 
	  ELSE BASE.ZCGDTNOTA
 END AS DATA_FORMATADA,
 COUNT(DISTINCT BASE.ZCGQMNUM) AS QTDE,
 SUM(MP.ZCGMTVCOB) AS MONT_VENC,
SUM(MP.PECLD_CONS) AS PECLD,
 CASE WHEN UPPER(BASE.ZCGTXTCOD) LIKE '%TELE%' OR BASE.ZCGCTTRAB = 'RPT161' OR LEFT(RIGHT(CL.ZCGUNLEIT,3),1)='R' THEN 'REMOTO'
 	  WHEN UPPER(BASE.ZCGTXTCOD) LIKE '% PRONTIDAO' AND LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') AND BASE.ZCGTPNOTA IN ('CS','CA') THEN 'PRONTIDAO'
	  WHEN LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') THEN 'STC'
	  ELSE 'EPS'
 END AS TURMA
 
FROM CLB_CCS_ICC.ZCT_DS_TAB004 AS BASE
 	
LEFT JOIN (SELECT DISTINCT ZCGACCOUN, ZCGMTVCOB, PECLD_CONS, DATA_CRIACAO 
		 FROM CLB142840.MPRED_HIST
		 WHERE DATA_CRIACAO BETWEEN ADD_DAYS((ADD_MONTHS(NEXT_DAY(LAST_DAY(CURRENT_DATE)),-2)),-6) AND (CURRENT_DATE)
		 ORDER BY DATA_CRIACAO DESC
		 ) AS MP
	ON  BASE.ZCGACCOUN = MP.ZCGACCOUN
	AND MP.DATA_CRIACAO BETWEEN ADD_DAYS(BASE.ZCGDTNOTA,-6) AND BASE.ZCGDTNOTA

LEFT JOIN CLP123432.PLANILHAO_CLIENTE CL ON BASE.ZCGACCOUN = CL.ZCGACCOUN  

LEFT JOIN CLB142840.CT_PRONT AS CT 
	ON BASE.ZCGCTTRAB = CT.CT AND ((BASE.ZCGDTFINA BETWEEN CT.DE AND CT.ATE) OR (BASE.ZCGDTFINA='19000101' AND BASE.ZCGDTNOTA BETWEEN CT.DE AND CT.ATE))
        
	


WHERE   (BASE.ZCGTPNOTA IN ('CS','CA') OR (BASE.ZCGTPNOTA = 'CB' AND UPPER(BASE.ZCGTXTCOD) NOT LIKE '%PED%'))
	AND BASE.ZCGDTNOTA BETWEEN (ADD_MONTHS(NEXT_DAY(LAST_DAY(CURRENT_DATE)),-2)) AND (CURRENT_DATE)
	AND BASE.ZCGQMNUM NOT IN (SELECT DISTINCT ZCGQMNUM FROM CLB142840.B100) 
	AND BASE.ZCGCTTRAB NOT IN ('JF1521','1LA000')
	
	
	
GROUP BY CL.REGIONAL40,	CL.SETOR40, CL.UTD40,
	BASE.ZCGDTNOTA,
	BASE.ZCGTPNOTA,
	
	 CASE WHEN (WEEKDAY(BASE.ZCGDTNOTA) < 5 AND BASE.ZCGHRNOTA > '15') OR WEEKDAY(BASE.ZCGDTNOTA) = 6 THEN NEXT_DAY(BASE.ZCGDTNOTA)
		  WHEN  WEEKDAY(BASE.ZCGDTNOTA) = 5 AND BASE.ZCGHRNOTA > '15' THEN ADD_DAYS(BASE.ZCGDTNOTA,2)
		  ELSE BASE.ZCGDTNOTA
	 END,
	 CASE WHEN UPPER(BASE.ZCGTXTCOD) LIKE '%TELE%' OR BASE.ZCGCTTRAB = 'RPT161' OR LEFT(RIGHT(CL.ZCGUNLEIT,3),1)='R' THEN 'REMOTO'
		  WHEN UPPER(BASE.ZCGTXTCOD) LIKE '% PRONTIDAO' AND LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') AND BASE.ZCGTPNOTA IN ('CS','CA') THEN 'PRONTIDAO'
		  WHEN LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') THEN 'STC'
		  ELSE 'EPS'
	 END
	
ORDER BY 
	ZCGDTNOTA
	)
	WHERE TURMA <> 'REMOTO'
	GROUP BY 
	UTD40 ,TURMA, ZCGTPNOTA,ZCGDTNOTA
	
	) AS BASE_GERADAS
	
	
	
	
	
	
	
	
	
	
	LEFT JOIN (
	SELECT 

UTD40 AS UTD,TURMA, 



SUM(QTDE) AS QTD_EXECUTADAS, 
SUM(PECLD) AS PECLD_EXECUTADAS,  
SUM(PECLD)/SUM(QTDE) AS TICKET_PECLD_EXECUTADAS,
CASE 
	WHEN ZCGTPNOTA = 'CS' THEN 'CORTE' 
	WHEN ZCGTPNOTA = 'CA' THEN 'RECORTE'
	WHEN ZCGTPNOTA = 'CB' THEN 'BAIXA' END AS CARTEIRA,
ZCGDTNOTA

FROM (
SELECT 
 CL.REGIONAL40,
 CL.SETOR40,
 CL.UTD40,	 

 BASE.ZCGTPNOTA,
 BASE.ZCGDTNOTA,
 
 BASE.ZCGDTENCE,

 COUNT(DISTINCT BASE.ZCGQMNUM) AS QTDE,
 SUM(MP.ZCGMTVCOB) AS MONT_VENC,
SUM(MP.PECLD_CONS) AS PECLD,
 CASE WHEN UPPER(BASE.ZCGTXTCOD) LIKE '%TELE%' OR BASE.ZCGCTTRAB = 'RPT161' OR LEFT(RIGHT(CL.ZCGUNLEIT,3),1)='R' THEN 'REMOTO'
 	  WHEN UPPER(BASE.ZCGTXTCOD) LIKE '% PRONTIDAO' AND LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') AND BASE.ZCGTPNOTA IN ('CS','CA') THEN 'PRONTIDAO'

	  WHEN LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') THEN 'STC'
	  ELSE 'EPS'
 END AS TURMA
 
FROM CLB_CCS_ICC.ZCT_DS_TAB004 AS BASE
 	
LEFT JOIN (SELECT DISTINCT ZCGACCOUN, ZCGMTVCOB, PECLD_CONS, DATA_CRIACAO 
		 FROM CLB142840.MPRED_HIST
		 WHERE DATA_CRIACAO BETWEEN ADD_DAYS((ADD_MONTHS(NEXT_DAY(LAST_DAY(CURRENT_DATE)),-2)),-6) AND (CURRENT_DATE)
		 ORDER BY DATA_CRIACAO DESC
		 ) AS MP
	ON  BASE.ZCGACCOUN = MP.ZCGACCOUN
	AND MP.DATA_CRIACAO BETWEEN ADD_DAYS(BASE.ZCGDTNOTA,-6) AND BASE.ZCGDTNOTA

LEFT JOIN CLP123432.PLANILHAO_CLIENTE CL ON BASE.ZCGACCOUN = CL.ZCGACCOUN  

LEFT JOIN CLB142840.CT_PRONT AS CT --TABELA DE TURMAS DA PRONTIDAO
	ON BASE.ZCGCTTRAB = CT.CT AND ((BASE.ZCGDTFINA BETWEEN CT.DE AND CT.ATE) OR (BASE.ZCGDTFINA='19000101' AND BASE.ZCGDTNOTA BETWEEN CT.DE AND CT.ATE))



WHERE   (BASE.ZCGTPNOTA IN ('CS','CA') OR (BASE.ZCGTPNOTA = 'CB' AND UPPER(BASE.ZCGTXTCOD) NOT LIKE '%PED%'))
	AND BASE.ZCGDTENCE BETWEEN (ADD_MONTHS(NEXT_DAY(LAST_DAY(CURRENT_DATE)),-2)) AND (CURRENT_DATE)
	AND BASE.ZCGQMNUM NOT IN (SELECT DISTINCT ZCGQMNUM FROM CLB142840.B100) 
	AND BASE.ZCGCTTRAB NOT IN ('JF1521','1LA000') 
	AND BASE.ZCGUSRSTS = 'VREL'
	
	
	
GROUP BY CL.REGIONAL40,	CL.SETOR40, CL.UTD40,
	BASE.ZCGDTNOTA,
	BASE.ZCGTPNOTA,
	  BASE.ZCGDTENCE,
	 CASE WHEN UPPER(BASE.ZCGTXTCOD) LIKE '%TELE%' OR BASE.ZCGCTTRAB = 'RPT161' OR LEFT(RIGHT(CL.ZCGUNLEIT,3),1)='R' THEN 'REMOTO'
		  WHEN UPPER(BASE.ZCGTXTCOD) LIKE '% PRONTIDAO' AND LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') AND BASE.ZCGTPNOTA IN ('CS','CA') THEN 'PRONTIDAO'
		  WHEN LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') THEN 'STC'
		  ELSE 'EPS'
	 END
	
ORDER BY 
	BASE.ZCGDTENCE
	)
	WHERE TURMA <> 'REMOTO'
	GROUP BY 
	UTD40 ,TURMA, ZCGTPNOTA,ZCGDTNOTA

	
	) AS BASE_EXECUTADAS
	ON BASE_EXECUTADAS.UTD = BASE_GERADAS.UTD AND BASE_EXECUTADAS.TURMA = BASE_GERADAS.TURMA AND 
	BASE_EXECUTADAS.CARTEIRA = BASE_GERADAS.CARTEIRA AND BASE_EXECUTADAS.ZCGDTNOTA = BASE_GERADAS.ZCGDTNOTA
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
LEFT JOIN (
	

SELECT 
UTD40 AS UTD,TURMA, 
SUM(QTDE) AS QTD_ANULADAS, 


CASE 
	WHEN ZCGTPNOTA = 'CS' THEN 'CORTE' 
	WHEN ZCGTPNOTA = 'CA' THEN 'RECORTE'
	WHEN ZCGTPNOTA = 'CB' THEN 'BAIXA' END AS CARTEIRA,
ZCGDTNOTA
FROM (
SELECT 
 CL.REGIONAL40,
 CL.SETOR40,
 CL.UTD40,	 
 BASE.ZCGTPNOTA,
 BASE.ZCGDTNOTA,
 
 BASE.ZCGDTENCE,

 COUNT(DISTINCT BASE.ZCGQMNUM) AS QTDE,
 SUM(MP.ZCGMTVCOB) AS MONT_VENC,
SUM(MP.PECLD_CONS) AS PECLD,
 CASE WHEN UPPER(BASE.ZCGTXTCOD) LIKE '%TELE%' OR BASE.ZCGCTTRAB = 'RPT161' OR LEFT(RIGHT(CL.ZCGUNLEIT,3),1)='R' THEN 'REMOTO'
 	  WHEN UPPER(BASE.ZCGTXTCOD) LIKE '% PRONTIDAO' AND BASE.ZCGTPNOTA IN ('CS','CA') THEN 'PRONTIDAO'

	  WHEN LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') THEN 'STC'
	  ELSE 'EPS'
 END AS TURMA
 
FROM CLB_CCS_ICC.ZCT_DS_TAB004 AS BASE
 	
LEFT JOIN (SELECT DISTINCT ZCGACCOUN, ZCGMTVCOB, PECLD_CONS, DATA_CRIACAO 
		 FROM CLB142840.MPRED_HIST
		 WHERE DATA_CRIACAO BETWEEN ADD_DAYS((ADD_MONTHS(NEXT_DAY(LAST_DAY(CURRENT_DATE)),-2)),-6) AND (CURRENT_DATE)
		 ORDER BY DATA_CRIACAO DESC
		 ) AS MP
	ON  BASE.ZCGACCOUN = MP.ZCGACCOUN
	AND MP.DATA_CRIACAO BETWEEN ADD_DAYS(BASE.ZCGDTNOTA,-6) AND BASE.ZCGDTNOTA

LEFT JOIN CLP123432.PLANILHAO_CLIENTE CL ON BASE.ZCGACCOUN = CL.ZCGACCOUN  

LEFT JOIN CLB142840.CT_PRONT AS CT --TABELA DE TURMAS DA PRONTIDAO
	ON BASE.ZCGCTTRAB = CT.CT AND ((BASE.ZCGDTFINA BETWEEN CT.DE AND CT.ATE) OR (BASE.ZCGDTFINA='19000101' AND BASE.ZCGDTNOTA BETWEEN CT.DE AND CT.ATE))


WHERE   (BASE.ZCGTPNOTA IN ('CS','CA') OR (BASE.ZCGTPNOTA = 'CB' AND UPPER(BASE.ZCGTXTCOD) NOT LIKE '%PED%'))
	AND BASE.ZCGDTNOTA BETWEEN (ADD_MONTHS(NEXT_DAY(LAST_DAY(CURRENT_DATE)),-2)) AND (CURRENT_DATE)
	AND BASE.ZCGQMNUM NOT IN (SELECT DISTINCT ZCGQMNUM FROM CLB142840.B100) 
	AND BASE.ZCGCTTRAB NOT IN ('JF1521','1LA000') 
	AND BASE.ZCGUSRSTS IN ('NVIS','CANC','ANUL')
	
	
	
GROUP BY CL.REGIONAL40,	CL.SETOR40, CL.UTD40,
	BASE.ZCGDTNOTA,
	BASE.ZCGTPNOTA,
	  BASE.ZCGDTENCE,
	 CASE WHEN UPPER(BASE.ZCGTXTCOD) LIKE '%TELE%' OR BASE.ZCGCTTRAB = 'RPT161' OR LEFT(RIGHT(CL.ZCGUNLEIT,3),1)='R' THEN 'REMOTO'
		  WHEN UPPER(BASE.ZCGTXTCOD) LIKE '% PRONTIDAO' AND BASE.ZCGTPNOTA IN ('CS','CA') THEN 'PRONTIDAO'
		  WHEN LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') THEN 'STC'
		  ELSE 'EPS'
	 END
	
ORDER BY 
	BASE.ZCGDTENCE
	)
	WHERE TURMA <> 'REMOTO'

	GROUP BY 
	UTD40 ,TURMA, ZCGTPNOTA,ZCGDTNOTA



) AS BASE_ANULADAS
	ON BASE_ANULADAS.UTD = BASE_GERADAS.UTD AND BASE_ANULADAS.TURMA = BASE_GERADAS.TURMA AND 
	BASE_ANULADAS.CARTEIRA = BASE_GERADAS.CARTEIRA AND BASE_ANULADAS.ZCGDTNOTA = BASE_GERADAS.ZCGDTNOTA
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	LEFT JOIN (SELECT 

UTD40 AS UTD,TURMA, 
--ZCGTPNOTA AS TIPO_NOTA, 
SUM(QTDE) AS QTD_DEFASAGEM, 
CASE 
	WHEN ZCGTPNOTA = 'CS' THEN 'CORTE' 
	WHEN ZCGTPNOTA = 'CA' THEN 'RECORTE'
	WHEN ZCGTPNOTA = 'CB' THEN 'BAIXA' END AS CARTEIRA,
ZCGDTNOTA
FROM (

SELECT 
 CL.REGIONAL40,
 CL.SETOR40,
 CL.UTD40,	 

 BASE.ZCGTPNOTA,
 BASE.ZCGDTNOTA,

 
 
 CASE WHEN (WEEKDAY(BASE.ZCGDTNOTA) < 5 AND BASE.ZCGHRNOTA > '15') OR WEEKDAY(BASE.ZCGDTNOTA) = 6 THEN NEXT_DAY(BASE.ZCGDTNOTA) 
	  WHEN  WEEKDAY(BASE.ZCGDTNOTA) = 5 AND BASE.ZCGHRNOTA > '15' THEN ADD_DAYS(BASE.ZCGDTNOTA,2) 
	  ELSE BASE.ZCGDTNOTA
 END AS DATA_FORMATADA,
 COUNT(DISTINCT BASE.ZCGQMNUM) AS QTDE,
 SUM(MP.ZCGMTVCOB) AS MONT_VENC,
SUM(MP.PECLD_CONS) AS PECLD,
 CASE WHEN UPPER(BASE.ZCGTXTCOD) LIKE '%TELE%' OR BASE.ZCGCTTRAB = 'RPT161' OR LEFT(RIGHT(CL.ZCGUNLEIT,3),1)='R' THEN 'REMOTO'
 	  WHEN UPPER(BASE.ZCGTXTCOD) LIKE '% PRONTIDAO' AND LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') AND BASE.ZCGTPNOTA IN ('CS','CA') THEN 'PRONTIDAO'
	  WHEN LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') THEN 'STC'
	  ELSE 'EPS'
 END AS TURMA
 
FROM CLB_CCS_ICC.ZCT_DS_TAB004 AS BASE
 	
LEFT JOIN (SELECT DISTINCT ZCGACCOUN, ZCGMTVCOB, PECLD_CONS, DATA_CRIACAO 
		 FROM CLB142840.MPRED_HIST
		 WHERE DATA_CRIACAO BETWEEN ADD_DAYS((ADD_MONTHS(NEXT_DAY(LAST_DAY(CURRENT_DATE)),-2)),-6) AND (CURRENT_DATE)
		 ORDER BY DATA_CRIACAO DESC
		 ) AS MP
	ON  BASE.ZCGACCOUN = MP.ZCGACCOUN
	AND MP.DATA_CRIACAO BETWEEN ADD_DAYS(BASE.ZCGDTNOTA,-6) AND BASE.ZCGDTNOTA

LEFT JOIN CLP123432.PLANILHAO_CLIENTE CL ON BASE.ZCGACCOUN = CL.ZCGACCOUN  

LEFT JOIN CLB142840.CT_PRONT AS CT 
	ON BASE.ZCGCTTRAB = CT.CT AND ((BASE.ZCGDTFINA BETWEEN CT.DE AND CT.ATE) OR (BASE.ZCGDTFINA='19000101' AND BASE.ZCGDTNOTA BETWEEN CT.DE AND CT.ATE))
        
	LEFT JOIN ( SELECT ZCGACCOUN,AH.DATA_PEDIDO,AH.FLAG_DEF AS FLAG_DEF_ATENA FROM CLB961920.ATENA_HIST AH
	WHERE FLAG_DEF = 'S') AS AH
	ON  AH.ZCGACCOUN = BASE.ZCGACCOUN AND (ADD_DAYS(AH.DATA_PEDIDO, -1) = BASE.ZCGDTNOTA OR ADD_DAYS(AH.DATA_PEDIDO, 0) = BASE.ZCGDTNOTA OR ADD_DAYS(AH.DATA_PEDIDO, -2) = BASE.ZCGDTNOTA)
	
	LEFT JOIN ( SELECT ZCGACCOUN,CH.DATA_PEDIDO,CH.FLAG_DEF AS FLAG_DEF_CLUSTER FROM CLB142840.CLUSTER_HIST CH
	WHERE FLAG_DEF = 'S') AS CH
	ON  CH.ZCGACCOUN = BASE.ZCGACCOUN AND (ADD_DAYS(CH.DATA_PEDIDO, -1) = BASE.ZCGDTNOTA OR ADD_DAYS(CH.DATA_PEDIDO, 0) = BASE.ZCGDTNOTA OR ADD_DAYS(CH.DATA_PEDIDO, -2) = BASE.ZCGDTNOTA)

WHERE   (BASE.ZCGTPNOTA IN ('CS','CA') OR (BASE.ZCGTPNOTA = 'CB' AND UPPER(BASE.ZCGTXTCOD) NOT LIKE '%PED%'))
	AND BASE.ZCGDTNOTA BETWEEN (ADD_MONTHS(NEXT_DAY(LAST_DAY(CURRENT_DATE)),-2)) AND (CURRENT_DATE)
	AND BASE.ZCGQMNUM NOT IN (SELECT DISTINCT ZCGQMNUM FROM CLB142840.B100) 
	AND BASE.ZCGCTTRAB NOT IN ('JF1521','1LA000')
	AND (FLAG_DEF_ATENA = 'S' OR FLAG_DEF_CLUSTER ='S')

	
GROUP BY CL.REGIONAL40,	CL.SETOR40, CL.UTD40,
	BASE.ZCGDTNOTA,
	BASE.ZCGTPNOTA,
	 CASE WHEN (WEEKDAY(BASE.ZCGDTNOTA) < 5 AND BASE.ZCGHRNOTA > '15') OR WEEKDAY(BASE.ZCGDTNOTA) = 6 THEN NEXT_DAY(BASE.ZCGDTNOTA)
		  WHEN  WEEKDAY(BASE.ZCGDTNOTA) = 5 AND BASE.ZCGHRNOTA > '15' THEN ADD_DAYS(BASE.ZCGDTNOTA,2)
		  ELSE BASE.ZCGDTNOTA
	 END,
	 CASE WHEN UPPER(BASE.ZCGTXTCOD) LIKE '%TELE%' OR BASE.ZCGCTTRAB = 'RPT161' OR LEFT(RIGHT(CL.ZCGUNLEIT,3),1)='R' THEN 'REMOTO'
		  WHEN UPPER(BASE.ZCGTXTCOD) LIKE '% PRONTIDAO' AND LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') AND BASE.ZCGTPNOTA IN ('CS','CA') THEN 'PRONTIDAO'
		  WHEN LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') THEN 'STC'
		  ELSE 'EPS'
	 END
	 
	 
ORDER BY 
	ZCGDTNOTA
	)
	WHERE TURMA <> 'REMOTO'
	GROUP BY 
	UTD40 ,TURMA, ZCGTPNOTA,ZCGDTNOTA
	
	) AS BASE_DEFASAGEM
	ON BASE_DEFASAGEM.UTD = BASE_GERADAS.UTD AND BASE_DEFASAGEM.TURMA = BASE_GERADAS.TURMA AND 
	BASE_DEFASAGEM.CARTEIRA = BASE_GERADAS.CARTEIRA AND BASE_DEFASAGEM.ZCGDTNOTA = BASE_GERADAS.ZCGDTNOTA

	
	)
WHERE ZCGDTNOTA > ADD_DAYS(CURRENT_DATE,-20) AND ZCGDTNOTA < CURRENT_DATE
order by ZCGDTNOTA
	
	
	
	
	
	
	
	
	
	
	
	
	

