SELECT CARTEIRA, UTD, SUM(QTD_SUSCETIVEIS) AS QTD_SUSCETIVEIS,SUM(PECLD) AS PECLD, SUM(PECLD)/SUM(QTD_SUSCETIVEIS) AS TICKET_PECLD FROM (
--ABAIXO ORIGINAL POR ZONA

SELECT 
UTD,
ZONA, 
CASE WHEN ACAO = 'DISJ' THEN 'DISJUNTOR' ELSE ACAO END AS CARTEIRA,
COUNT(SUSCETIVEIS.ZCGACCOUN) AS QTD_SUSCETIVEIS ,SUM(ZCGMTVCOB) AS VALOR_COBRAVEL, SUM(PECLD) AS PECLD, (SUM(PECLD)/COUNT(SUSCETIVEIS.ZCGACCOUN)) AS TICKET_PECLD, (SUM(ZCGMTVCOB)/COUNT(SUSCETIVEIS.ZCGACCOUN)) AS TICKET_COBRAVEL FROM CLB961920.SUSCETIVEIS
LEFT JOIN (SELECT ZCGVKONT AS ZCGACCOUN, SUM(ZCGPECLDALOC) AS PECLD
FROM CLB_CCS_ICC.ZCT_DS_CARGA_AGING_COELBA
GROUP BY ZCGVKONT) AS PDD
ON PDD.ZCGACCOUN = SUSCETIVEIS.ZCGACCOUN
WHERE ZONA IS NOT NULL
AND DATAREF = ADD_DAYS(CURRENT_DATE,0) 
GROUP BY DATAREF,ACAO,UTD,ZONA

--ACIMA ORIGINAL POR ZONA
)
GROUP BY UTD, CARTEIRA
