
SELECT UTD,TURMA, CARTEIRA,DATA_PEDIDO, COUNT(ZCGACCOUN) AS NOTAS_ESPERADAS_ATENA,COUNT(NOTA) AS NOTAS_GERADAS_TAB4,COUNT(ZCGACCOUN) -COUNT(NOTA) AS DEFASAGEM_GERACAO FROM (
SELECT 
	AH.ZCGACCOUN,
	ZCGUTD AS UTD,
	ZCGMTVCOB,
	CASE WHEN CARTEIRA = 'DISJUNTOR' OR CARTEIRA = 'DISJUNTOR MIX' THEN 'DISJUNTOR' 
	WHEN CARTEIRA = 'RECORTE MIX' OR CARTEIRA = 'RECORTE' THEN 'RECORTE'
	WHEN CARTEIRA = 'CONVENCIONAL' THEN 'CORTE'
	WHEN CARTEIRA = 'BAIXA MIX' OR CARTEIRA = 'BAIXA' THEN 'BAIXA' END AS CARTEIRA,
	TURMA,
	DATA_PEDIDO,
	DAYOFWEEK(DATA_PEDIDO) AS DIA_SEMANA,
	ZCGIDZONA AS ZONA,
	FLAG_DEF,
	NOTA,
	TIPO_NOTA
FROM CLB961920.ATENA_HIST AH
LEFT JOIN (SELECT TAB004.ZCGQMNUM AS NOTA,
	TAB004.ZCGDTCRIA AS ZCGDTCRIA,
	TAB004.ZCGINSTAL AS INSTALACAO,
	TAB004.ZCGPEDIDO AS PEDIDO,
	TAB004.ZCGACCOUN,
	TAB004.ZCGTPNOTA AS TIPO_NOTA
FROM CLB_CCS_ICC.ZCT_DS_TAB004 TAB004
WHERE ZCGTPNOTA IN ('CA','CS','CB')) TAB004
ON TAB004.ZCGACCOUN = AH.ZCGACCOUN AND 
(ZCGDTCRIA >= ADD_DAYS(DATA_PEDIDO, 0) AND ZCGDTCRIA <= ADD_DAYS(DATA_PEDIDO, 1) )
WHERE DATA_PEDIDO = '{data_consulta}'

UNION 

SELECT 
	CH.ZCGACCOUN,
	PC.UTD,
	ZCGMTVCOB,
	CASE WHEN CARTEIRA = 'BAIXA MIX' OR CARTEIRA = 'BAIXA' THEN 'BAIXA' 
	WHEN CARTEIRA = 'RECORTE MIX' OR CARTEIRA = 'RECORTE' THEN 'RECORTE'
	WHEN CARTEIRA = 'DISJUNTOR' OR CARTEIRA = 'DISJ MIX' THEN 'DISJUNTOR'
	WHEN CARTEIRA = 'CONVENCIONAL' THEN 'CORTE'
	WHEN (CARTEIRA = 'TOP5' OR CARTEIRA = 'TOP_STC')AND DAYOFWEEK(DATA_PEDIDO) = 4 THEN 'RECORTE'
	WHEN (CARTEIRA = 'TOP5' OR CARTEIRA = 'TOP_STC') AND DAYOFWEEK(DATA_PEDIDO) <> 4 THEN 'CORTE'
	WHEN (CARTEIRA = 'PROPRIA') AND DAYOFWEEK(DATA_PEDIDO) = 4 THEN 'RECORTE'
	WHEN (CARTEIRA = 'PROPRIA') AND DAYOFWEEK(DATA_PEDIDO) <> 4 THEN 'CORTE' END AS CARTEIRA,
	
	CASE WHEN CARTEIRA = 'BAIXA MIX' OR CARTEIRA = 'BAIXA' THEN 'EPS' 
	WHEN CARTEIRA = 'RECORTE MIX' OR CARTEIRA = 'RECORTE' THEN 'EPS'
	WHEN CARTEIRA = 'DISJ MIX' OR CARTEIRA = 'DISJUNTOR' THEN 'EPS'
	WHEN CARTEIRA = 'CONVENCIONAL' THEN 'EPS'
	WHEN (CARTEIRA = 'TOP5' ) THEN 'EPS'
	WHEN ( CARTEIRA = 'TOP_STC')  THEN 'STC'
	WHEN (CARTEIRA = 'PROPRIA') THEN 'STC' END AS TURMA,
	DATA_PEDIDO,
	DAYOFWEEK(DATA_PEDIDO) AS DIA_SEMANA,
	ZCGIDZONA AS ZONA,
	FLAG_DEF,
	NOTA,
	TIPO_NOTA
FROM CLB142840.CLUSTER_HIST CH
LEFT JOIN (SELECT TAB004.ZCGQMNUM AS NOTA,
	TAB004.ZCGDTCRIA AS ZCGDTCRIA,
	TAB004.ZCGINSTAL AS INSTALACAO,
	TAB004.ZCGPEDIDO AS PEDIDO,
	TAB004.ZCGACCOUN,
	TAB004.ZCGTPNOTA AS TIPO_NOTA
FROM CLB_CCS_ICC.ZCT_DS_TAB004 TAB004
WHERE ZCGTPNOTA IN ('CA','CS','CB')) TAB004
ON TAB004.ZCGACCOUN = CH.ZCGACCOUN AND 
(ZCGDTCRIA >= ADD_DAYS(DATA_PEDIDO, 0) AND ZCGDTCRIA <= ADD_DAYS(DATA_PEDIDO, 1) )

LEFT JOIN (SELECT DISTINCT UTD40 AS UTD, ZCGACCOUN FROM CLP123432.PLANILHAO_CLIENTE PC WHERE PC.SEQCC = 1) AS PC
ON PC.ZCGACCOUN = CH.ZCGACCOUN


WHERE CARTEIRA <> 'PRONTIDAO'
AND CH.ZCGACCOUN NOT IN (SELECT DISTINCT AH.ZCGACCOUN FROM CLB961920.ATENA_HIST AH WHERE DATA_PEDIDO = '{data_consulta}')
AND DATA_PEDIDO = '{data_consulta}'
AND FLAG_DEF = 'N'
)


WHERE FLAG_DEF = 'N'
AND DATA_PEDIDO = '{data_consulta}'
GROUP BY UTD, DATA_PEDIDO,TURMA, CARTEIRA