SELECT 
 CL.REGIONAL40,
 CL.SETOR40,
 CL.UTD40,	 
 --ZONA,
 CL.MUNICIPIO,
CL.ZCGBAIRR AS BAIRRO, 
CASE WHEN ZCGTPNOTA = 'CS' THEN 'CORTE' 
WHEN ZCGTPNOTA = 'CA' THEN 'RECORTE'
WHEN ZCGTPNOTA = 'CB' THEN 'BAIXA' END AS CARTEIRA,
 BASE.ZCGTPNOTA,
 BASE.ZCGDTNOTA,
 CASE WHEN (WEEKDAY(BASE.ZCGDTNOTA) < 5 AND BASE.ZCGHRNOTA > '15') OR WEEKDAY(BASE.ZCGDTNOTA) = 6 THEN NEXT_DAY(BASE.ZCGDTNOTA) 
	  WHEN  WEEKDAY(BASE.ZCGDTNOTA) = 5 AND BASE.ZCGHRNOTA > '15' THEN ADD_DAYS(BASE.ZCGDTNOTA,2) 
	  ELSE BASE.ZCGDTNOTA
 END AS DATA_FORMATADA,
BASE.ZCGQMNUM,
 ZCGUSRSTS,

 MP.ZCGMTVCOB,
MP.PECLD_CONS,
 CASE WHEN UPPER(BASE.ZCGTXTCOD) LIKE '%TELE%' OR BASE.ZCGCTTRAB = 'RPT161' OR LEFT(RIGHT(CL.ZCGUNLEIT,3),1)='R' THEN 'REMOTO'
 	  WHEN UPPER(BASE.ZCGTXTCOD) LIKE '% PRONTIDAO' AND LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') AND BASE.ZCGTPNOTA IN ('CS','CA') THEN 'PRONTIDAO'
	  WHEN LEFT(BASE.ZCGCTTRAB,1) IN ('1','2') THEN 'STC'
	  ELSE 'EPS'
 END AS TURMA
 
FROM CLB_CCS_ICC.ZCT_DS_TAB004 AS BASE
 	
LEFT JOIN (SELECT DISTINCT ZCGACCOUN, ZCGMTVCOB, PECLD_CONS, DATA_CRIACAO 
		 FROM CLB142840.MPRED_HIST
		 WHERE DATA_CRIACAO BETWEEN ADD_DAYS((ADD_MONTHS(NEXT_DAY(LAST_DAY(CURRENT_DATE)),-1)),-40) AND (CURRENT_DATE)
		 ORDER BY DATA_CRIACAO DESC
		 ) AS MP
	ON  BASE.ZCGACCOUN = MP.ZCGACCOUN
	AND MP.DATA_CRIACAO BETWEEN ADD_DAYS(BASE.ZCGDTNOTA,-6) AND BASE.ZCGDTNOTA

LEFT JOIN CLP123432.PLANILHAO_CLIENTE CL ON BASE.ZCGACCOUN = CL.ZCGACCOUN  

LEFT JOIN CLB142840.CT_PRONT AS CT 
	ON BASE.ZCGCTTRAB = CT.CT AND ((BASE.ZCGDTFINA BETWEEN CT.DE AND CT.ATE) OR (BASE.ZCGDTFINA='19000101' AND BASE.ZCGDTNOTA BETWEEN CT.DE AND CT.ATE))
        
	
LEFT JOIN (SELECT ZCGACCOUN, ZONA, RANK() OVER ( PARTITION BY ZCGACCOUN ORDER BY DATAREF DESC ) AS rank_sus FROM CLB961920.SUSCETIVEIS
WHERE DATAREF < ADD_DAYS(CURRENT_DATE,40) ) SUSCETIVEIS_ZONAS
ON SUSCETIVEIS_ZONAS.ZCGACCOUN = BASE.ZCGACCOUN AND rank_sus = 1

WHERE   (BASE.ZCGTPNOTA IN ('CS','CA') OR (BASE.ZCGTPNOTA = 'CB' AND UPPER(BASE.ZCGTXTCOD) NOT LIKE '%PED%'))
	AND BASE.ZCGDTNOTA BETWEEN (ADD_MONTHS(NEXT_DAY(LAST_DAY(CURRENT_DATE)),-2)) AND (CURRENT_DATE)
	AND BASE.ZCGQMNUM NOT IN (SELECT DISTINCT ZCGQMNUM FROM CLB142840.B100) 
	AND BASE.ZCGCTTRAB NOT IN ('JF1521','1LA000')
	AND ZCGDTNOTA > ADD_DAYS(CURRENT_DATE,-30) 