SELECT ZCGNMLOGR,ZCGBAIRR,MUNICIPIO,"cluster" AS PACOTE,BASE.ZCGACCOUN,PC.ZCGLATITU as LATITUDE,PC.ZCGLONGIT as LONGITUDE,UTD,ZCGMTVCOB AS MONTANTE,PECLD,CARTEIRA,TURMA,DATA_PEDIDO,ZONA,NOTA,TIPO_NOTA,
RANK() OVER ( PARTITION BY UTD ORDER BY PECLD DESC ) AS RANK_PECLD,
RIGHT("cluster",1) AS ATALHO_PACOTE,
RIGHT("cluster",2) AS ATALHO_PACOTE_2
FROM (
SELECT 
	AH."cluster", 
	AH.ZCGACCOUN,
	ZCGUTD AS UTD,
	ZCGMTVCOB,
	ZCGPECLD AS PECLD,
	CASE WHEN CARTEIRA = 'DISJUNTOR' OR CARTEIRA = 'DISJUNTOR MIX' THEN 'DISJUNTOR' 
	WHEN CARTEIRA = 'RECORTE MIX' OR CARTEIRA = 'RECORTE' THEN 'RECORTE'
	WHEN CARTEIRA = 'CONVENCIONAL' THEN 'CORTE'
	WHEN CARTEIRA = 'BAIXA MIX' OR CARTEIRA = 'BAIXA' THEN 'BAIXA' END AS CARTEIRA,
	TURMA,
	DATA_PEDIDO,
	DAYOFWEEK(DATA_PEDIDO) AS DIA_SEMANA,
	ZCGIDZONA AS ZONA,
	FLAG_DEF,
	'-' AS NOTA,
	CASE WHEN CARTEIRA = 'DISJUNTOR' OR CARTEIRA = 'DISJUNTOR MIX' OR CARTEIRA = 'CONVENCIONAL' THEN 'CS'
	WHEN CARTEIRA = 'RECORTE MIX' OR CARTEIRA = 'RECORTE' THEN 'CA' 
	WHEN CARTEIRA = 'BAIXA MIX' OR CARTEIRA = 'BAIXA' THEN 'CB'
	END AS TIPO_NOTA
FROM CLB961920.ATENA_HIST AH

WHERE DATA_PEDIDO =  '{data_mapa_folium}'
AND FLAG_DEF = 'N'

UNION 

SELECT 
	CH."cluster",
	CH.ZCGACCOUN,
	PC.UTD,
	ZCGMTVCOB,
	NULL AS PECLD,
	CASE WHEN CARTEIRA = 'BAIXA MIX' OR CARTEIRA = 'BAIXA' THEN 'BAIXA' 
	WHEN CARTEIRA = 'RECORTE MIX' OR CARTEIRA = 'RECORTE' THEN 'RECORTE'
	WHEN CARTEIRA = 'DISJUNTOR' OR CARTEIRA = 'DISJ MIX' THEN 'DISJUNTOR'
	WHEN CARTEIRA = 'CONVENCIONAL' THEN 'CORTE'
	WHEN (CARTEIRA = 'TOP5' OR CARTEIRA = 'TOP_STC')AND DAYOFWEEK(DATA_PEDIDO) = 4 THEN 'RECORTE'
	WHEN (CARTEIRA = 'TOP5' OR CARTEIRA = 'TOP_STC') AND DAYOFWEEK(DATA_PEDIDO) <> 4 THEN 'CORTE'
	WHEN (CARTEIRA = 'PROPRIA') AND DAYOFWEEK(DATA_PEDIDO) = 4 THEN 'RECORTE'
	WHEN (CARTEIRA = 'PROPRIA') AND DAYOFWEEK(DATA_PEDIDO) <> 4 THEN 'CORTE' END AS CARTEIRA,
	
	CASE WHEN CARTEIRA = 'BAIXA MIX' OR CARTEIRA = 'BAIXA' THEN 'EPS' 
	WHEN CARTEIRA = 'RECORTE MIX' OR CARTEIRA = 'RECORTE' THEN 'EPS'
	WHEN CARTEIRA = 'DISJ MIX' OR CARTEIRA = 'DISJUNTOR' THEN 'EPS'
	WHEN CARTEIRA = 'CONVENCIONAL' THEN 'EPS'
	WHEN (CARTEIRA = 'TOP5' ) THEN 'EPS'
	WHEN ( CARTEIRA = 'TOP_STC')  THEN 'STC'
	WHEN (CARTEIRA = 'PROPRIA') THEN 'STC' END AS TURMA,
	DATA_PEDIDO,
	DAYOFWEEK(DATA_PEDIDO) AS DIA_SEMANA,
	ZCGIDZONA AS ZONA,
	FLAG_DEF,
	'-' AS NOTA,
	CASE WHEN CARTEIRA = 'DISJUNTOR' OR CARTEIRA = 'DISJUNTOR MIX' OR CARTEIRA = 'DISJ MIX'  OR CARTEIRA = 'CONVENCIONAL' THEN 'CS'
	WHEN (CARTEIRA = 'PROPRIA') AND DAYOFWEEK(DATA_PEDIDO) = 4 THEN 'CA'
	WHEN (CARTEIRA = 'PROPRIA') AND DAYOFWEEK(DATA_PEDIDO) <> 4 THEN 'CS'
	WHEN (CARTEIRA = 'TOP5' OR CARTEIRA = 'TOP_STC')AND DAYOFWEEK(DATA_PEDIDO) = 4 THEN 'CA'
	WHEN (CARTEIRA = 'TOP5' OR CARTEIRA = 'TOP_STC') AND DAYOFWEEK(DATA_PEDIDO) <> 4 THEN 'CS'
	WHEN CARTEIRA = 'RECORTE MIX' OR CARTEIRA = 'RECORTE' THEN 'CA' 
	WHEN CARTEIRA = 'BAIXA MIX' OR CARTEIRA = 'BAIXA' THEN 'CB'
	END AS TIPO_NOTA
FROM CLB142840.CLUSTER_HIST CH


LEFT JOIN (SELECT DISTINCT UTD40 AS UTD, ZCGACCOUN FROM CLP123432.PLANILHAO_CLIENTE PC WHERE PC.SEQCC = 1) AS PC
ON PC.ZCGACCOUN = CH.ZCGACCOUN


WHERE CARTEIRA <> 'PRONTIDAO'
AND CH.ZCGACCOUN NOT IN (SELECT DISTINCT AH.ZCGACCOUN FROM CLB961920.ATENA_HIST AH WHERE DATA_PEDIDO = '{data_mapa_folium}')
AND DATA_PEDIDO = '{data_mapa_folium}'
AND FLAG_DEF = 'N'

) AS BASE
LEFT JOIN (
    SELECT 
        ZCGACCOUN,ZCGLATITU,ZCGLONGIT,MUNICIPIO
    FROM CLP123432.PLANILHAO_CLIENTE AS PC
    WHERE 
        SEQCC = 1
        AND ZCGLATITU IS NOT NULL
    ) PC 
ON PC.ZCGACCOUN = BASE.ZCGACCOUN

LEFT JOIN ( SELECT ZCGACCOUN,ZCGNMLOGR,ZCGBAIRR
FROM CLB_CCS_ICC.ZCT_DS_CLI001 CLI001 ) AS CLI001
ON CLI001.ZCGACCOUN = BASE.ZCGACCOUN

WHERE UTD = '{utd_mapa_folium}'
AND TURMA = '{turma_mapa_folium}'
