SELECT UTD,QTD_CLUSTER, QTD_MAX,ZONA, TURMA,CARTEIRA,TOTAL_ESPERADO_MAPA, DATA_PEDIDO FROM (
SELECT HMS.QTD_CLUSTER, HMS.QTD_MAX,HMS.UTD, HMS.ZONA, HMS.CARTEIRA,HMS.TURMA,SUM(TOTAL_ESPERADO_MAPA) AS TOTAL_ESPERADO_MAPA,NULL AS TOTAL_ESPERADO_ATENA, HMS.DATA_PEDIDO, DAYOFWEEK(DATA_PEDIDO) AS DIA_SEMANA, NULL AS FLAG_DEF

FROM (
SELECT HMS.QTD_CLUSTER, HMS.QTD_MAX,HMS.UTD,ZONA,CARTEIRA,TURMA,QTD_CLUSTER* QTD_MAX AS TOTAL_ESPERADO_MAPA,DATA_PEDIDO FROM CLB344173.HISTORICO_MAPA_SELECAO HMS
) HMS
WHERE  HMS.ZONA LIKE ('%0%') OR  HMS.ZONA LIKE ('%1%') OR HMS.ZONA  LIKE ('%2%') OR  HMS.ZONA LIKE ('%3%') OR  HMS.ZONA LIKE ('%4%')
GROUP BY HMS.UTD, HMS.ZONA, HMS.CARTEIRA,HMS.TURMA,HMS.DATA_PEDIDO,QTD_CLUSTER, QTD_MAX
)

-- TROCAR PARA O DIA SEGUINTE QUANDO FOR FERIADO
WHERE DATA_PEDIDO = '{data_consulta}'
--WHERE DATA_PEDIDO = '2022-09-07'
