SELECT DISTINCT
    PC.REGIONAL40,
    PC.SETOR40,
    PC.UTD40,
    PC.ZCGACCOUN,
    PC.ZCGINSTAL,
	DADOS_FATURAMENTO.ZCGDTDOCT AS FAT_ZCGDTDOCT,
	ARR.ZCGAMOUNTDIA AS ARR_ZCGAMOUNTDIA,
	ARR.ZCGDTCOMP AS ARR_ZCGDTCOMP,
	DADOS_FATURAMENTO.ZCGNOMED AS FAT_ZCGNOMED,
    PC.ZCGNUMMED,
    PC.ZCGSITUCC AS SIT_CC,
    PC.ZCGMODLIGA,
    CASE WHEN SUBSTRING(PC.ZCGUNLEIT,6,1) IN ('R','T') THEN SUBSTRING(PC.ZCGUNLEIT,6,1) ELSE 'N' END AS TELEMEDIDO,
    DS.ZCGMTSUSP AS MOTV_DOC_SUSP,
	DS.ZCGSTATUS AS STS_DOC_SUSP,
    NOTA_PENDENTE.ZCGTPNOTA AS TP_PEND,
    FCC001.ZCGAMOUNT AS MONT_CR,
    PDD.PECLD as PECLD_ATUAL, 
    FCC001.ZCGFLFRAU AS FLAG_FR,
    FR.ULT_FR,
    FR.MONT_FR,
    FR.ZCGTPDOCF AS TP_FRA,
    FR.ZCGFLPARC AS TEM_FRA_PARC,
    LT."ZCGNOTAL" AS NT_LEIT, 
    LT."ZCGDTLEIT" AS DT_LEIT,
    BC.ZCGCDBLOQ AS BLOQ_TIPO_CC,
    BF.ZCGCDBLOQ AS BLOQ_TIPO_FAT,
    NULL AS CART_INAD,
    CI.ZCGDTENCE AS DT_ULT_CI,
    tab_suscetivel.ZCGNNVLAD, 
    tab_suscetivel.ZCGAMOUNT AS VALOR_CORTE,
    PC.ZCGPROCADV,
    CASE WHEN PC.ZCGPROCADV IN ('NB','NA') THEN 'NAO_CORTAVEL' ELSE 'CORTAVEL' END AS CHECK_CORTE,
    PDD_2.CR_2 AS MONT_CR_2,
    PDD_2.PECLD_2 AS PECLD_ATUAL_2
FROM CLP123432.PLANILHAO_CLIENTE PC

LEFT JOIN (SELECT FAT001.ZCGACCOUN, FAT001.ZCGDTDOCT, FAT001.ZCGNOMED
FROM CLB_CCS_ICC.ZCT_DS_FAT001 AS FAT001
WHERE 	ZCGIDREFA IN ('B','R')
AND ZCGDTDOCT BETWEEN ADD_MONTHS(CURRENT_DATE,-12) AND CURRENT_DATE
AND ZCGACCOUN IN ({lista_consultar})) AS DADOS_FATURAMENTO
ON  DADOS_FATURAMENTO.ZCGACCOUN = PC.ZCGACCOUN

LEFT JOIN (SELECT ZCGVKONT AS ZCGACCOUN, SUM(ZCGPECLDALOC) AS PECLD
FROM CLB_CCS_ICC.ZCT_DS_CARGA_AGING_COELBA
GROUP BY ZCGVKONT) AS PDD
ON PDD.ZCGACCOUN = PC.ZCGACCOUN

LEFT JOIN (SELECT ZCGVKONT AS ZCGACCOUN,
SUM (ZCGBETRW) AS CR_2,
SUM (zcgpecldaloc) AS PECLD_2
FROM CLB_CCS_ICC.ZCT_DS_CARGA_AGING_COELBA
WHERE ZCGVKONT IN ({lista_consultar})
GROUP BY ZCGVKONT) AS PDD_2
ON PDD_2.ZCGACCOUN = PC.ZCGACCOUN

LEFT JOIN (SELECT TLE001.ZCGACCOUN, TLE001.ZCGNOTAL, TLE001.ZCGDTLEIT
FROM CLB_CCS_ICC.ZCT_DS_TLE001 TLE001
WHERE TLE001.ZCGDTLEIT BETWEEN ADD_MONTHS(CURRENT_DATE,-12) AND CURRENT_DATE
GROUP BY ZCGACCOUN,ZCGNOTAL,ZCGDTLEIT) as LT
ON LT.ZCGACCOUN = PC.ZCGACCOUN

LEFT JOIN (SELECT DISTINCT DUN001.ZCGACCOUN, DUN001.ZCGNNVLAD, DUN001.ZCGDTEMIS, DUN001.ZCGDTVENC, DUN001.ZCGAMOUNT, cli.ZCGBAIRR,
RANK() OVER ( PARTITION BY DUN001.ZCGACCOUN ORDER BY DUN001.ZCGDTVENC DESC ) AS prio
FROM CLB_CCS_ICC.ZCT_DS_DUN001 DUN001
LEFT JOIN clb_ccs_icc.zct_ds_cli001 AS cli ON  DUN001.ZCGACCOUN  = cli.ZCGACCOUN
WHERE DUN001.ZCGNNVLAD = 30 AND DUN001.ZCGACCOUN IN ({lista_consultar})) AS tab_suscetivel
ON PC.ZCGACCOUN = tab_suscetivel.ZCGACCOUN AND tab_suscetivel.prio = 1

LEFT JOIN 
			( SELECT ZCGACCOUN, SUM(ZCGAMOUNTDIA) AS ZCGAMOUNTDIA,ZCGDTCOMP
			  FROM "CLB_CCS_ICC"."ZCT_DS_FCO002"
			  WHERE ZCGDTCOMP BETWEEN ADD_MONTHS(CURRENT_DATE, -12) AND CURRENT_DATE
			    AND ZCGMTCOMP IN ('01','07')
GROUP BY ZCGDTCOMP,ZCGACCOUN,ZCGAMOUNTDIA) ARR
		 ON PC.ZCGACCOUN = ARR.ZCGACCOUN

LEFT JOIN (SELECT TAB004.ZCGACCOUN, TAB004.ZCGTPNOTA
FROM CLB_CCS_ICC.ZCT_DS_TAB004 TAB004
WHERE TAB004.ZCGTPNOTA = 'CI'
AND TAB004.ZCGUSRSTS IN ('CRIA', 'DESP', 'REDI', 'RETI', 'RLIB')
AND UPPER(TAB004.ZCGSYSSTS) NOT LIKE  UPPER('%MSEN%')
AND ZCGACCOUN IN ({lista_consultar})) NT_CI_PENDENTE
ON PC.ZCGACCOUN = NT_CI_PENDENTE.ZCGACCOUN

LEFT JOIN (SELECT SUBSTRING(ZCGOBJKEY,1,12) AS ZCGACCOUN, ZCGMTSUSP, ZCGSTATUS
FROM CLB_CCS_ICC.ZCT_DS_TAB011 TAB011
WHERE ULTI_SUSP = 1) AS DS
ON PC.ZCGACCOUN = DS.ZCGACCOUN

LEFT JOIN (SELECT TAB004.ZCGACCOUN, TAB004.ZCGTPNOTA
FROM CLB_CCS_ICC.ZCT_DS_TAB004 TAB004
WHERE TAB004.ZCGTPNOTA IN ('CA','CR','CS','CB')
AND TAB004.ZCGUSRSTS IN ('CRIA', 'DESP', 'REDI', 'RETI', 'RLIB')
AND UPPER(TAB004.ZCGSYSSTS) NOT LIKE  UPPER('%MSEN%')
AND ZCGACCOUN IN ({lista_consultar})) NOTA_PENDENTE
ON PC.ZCGACCOUN = NOTA_PENDENTE.ZCGACCOUN

LEFT JOIN CLB_CCS_ICC.ZCT_DS_FCC001 FCC001
ON FCC001.ZCGACCOUN = PC.ZCGACCOUN

LEFT JOIN (SELECT CTR001.ZCGACCOUN,  MAX(CTR001.ZCGDTREAL) AS FATURA_RECENTE, SUM(CTR001.ZCGAMOUNT) AS ZCGAMOUNT
FROM CLB_CCS_ICC.ZCT_DS_CTR001 AS CTR001 
WHERE (ZCGFLPARC = 'N')
GROUP BY "ZCGACCOUN") AS CM
ON PC.ZCGACCOUN = CM.ZCGACCOUN 

LEFT JOIN (SELECT CTR001.ZCGACCOUN,  max(CTR001.ZCGFLPARC) AS ZCGFLPARC, MAX(CTR001.ZCGDTREAL) AS ULT_FR, SUM(CTR001.ZCGAMOUNT) AS MONT_FR, MAX(CN.ZCGTPDOCF) AS ZCGTPDOCF
FROM CLB_CCS_ICC.ZCT_DS_CTR001 CTR001
LEFT JOIN "NEO_PEC"."neo.pec.data::MODEL.TABLES.ZCT_DS_FAT_IRREGULARIDADE" CN
ON  CTR001.ZCGACCOUN = CN.ZCGACCOUN
AND CTR001.ZCGDOCREF = CN.ZCGDOCREF
WHERE (CTR001.ZCGTIPDOC = 'FR')
GROUP BY CTR001.ZCGACCOUN) AS FR
ON PC.ZCGACCOUN = FR.ZCGACCOUN  

LEFT JOIN (SELECT DISTINCT BLQ001.ZCGACCOUN , BLQ001.ZCGCDBLOQ 
FROM CLB_CCS_ICC.ZCT_DS_BLQ001 BLQ001 
WHERE ZCGPCBLOQ <> 'ZN') AS BC
ON BC.ZCGACCOUN = PC.ZCGACCOUN
		
LEFT JOIN (SELECT DISTINCT ZCGACCOUN, MAX(ZCGCDBLOQ)  AS ZCGCDBLOQ
FROM CLB_CCS_ICC.ZCT_DS_BLQ002 
WHERE  ZCGPCBLOQ <> 'ZN'
GROUP BY ZCGACCOUN) AS BF
ON BF.ZCGACCOUN = PC.ZCGACCOUN	



LEFT JOIN (SELECT DISTINCT ZCGACCOUN, MAX(ZCGDTENCE) AS ZCGDTENCE  
FROM CLB_CCS_ICC.ZCT_DS_TAB004
WHERE ZCGTPNOTA IN ('CI') AND ZCGUSRSTS IN ('VREL')
GROUP BY ZCGACCOUN ) CI
ON PC.ZCGACCOUN = CI.ZCGACCOUN

LEFT JOIN (SELECT DISTINCT TAB004.ZCGACCOUN, MAX(TAB004.ZCGDTNOTA) AS ZCGDTNOTA
FROM CLB_CCS_ICC.ZCT_DS_TAB004 TAB004
WHERE TAB004.ZCGTPNOTA IN ('CB','CS') 
AND TAB004.ZCGDTNOTA BETWEEN '20220201' AND '20231231' 
AND TAB004.ZCGCREABY IN ('CLB344173','CLB142840','ETB348056','CLB961920') 
GROUP BY TAB004.ZCGACCOUN ) NOTAS_GERADAS_PR
ON PC.ZCGACCOUN = NOTAS_GERADAS_PR.ZCGACCOUN

LEFT JOIN (SELECT DISTINCT 
TAB004.ZCGACCOUN,
TAB004.ZCGQMNUM, 
TAB004.ZCGDTNOTA, 
TAB004.ZCGTPNOTA, 
TAB004.ZCGUSRSTS,
TAB004.ZCGCREABY 
FROM CLB_CCS_ICC.ZCT_DS_TAB004 TAB004
WHERE TAB004.ZCGTPNOTA IN ('CB','CS') 
AND TAB004.ZCGDTNOTA BETWEEN '20220201' AND '20231231' 
AND TAB004.ZCGCREABY IN ('CLB344173','CLB142840','ETB348056','CLB961920') 
AND TAB004.ZCGACCOUN IN ({lista_consultar})) DADOS_NOTAS_GERADAS_PR
ON DADOS_NOTAS_GERADAS_PR.ZCGDTNOTA = NOTAS_GERADAS_PR.ZCGDTNOTA AND DADOS_NOTAS_GERADAS_PR.ZCGACCOUN = PC.ZCGACCOUN

WHERE PC.ZCGACCOUN IN ({lista_consultar})
AND PC.SEQCC = 1

    
   
